CREATE SCHEMA party;

USE party;
CREATE TABLE CLIENTE(
    ID_CLIENTE int not null auto_increment,
    NOME_CLIENTE VARCHAR (50),
    FONE_CLIENTE VARCHAR (11),
    WHATSAPP VARCHAR (11),
    DATA_CADASTRO DATE,
    ENDERECO_CLIENTE VARCHAR (70),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE) 
);

CREATE TABLE FESTA (
    ID_FESTA INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT,
    DATA_FESTA DATE,
    HORA_INICIO_FESTA VARCHAR(4),
    HORA_FINAL_FESTA  VARCHAR(4),
    ENDERECO_FESTA VARCHAR (70),
    CONSTRAINT PK_FESTA PRIMARY KEY (ID_FESTA),
    CONSTRAINT FK_FESTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE TEMA (
    ID_TEMA INT NOT NULL AUTO_INCREMENT,
    NOME_TEMA VARCHAR(30),
    VALOR_TEMA DOUBLE,
    QUANTIDADE_TEMA INT,
    CONSTRAINT PK_TEMA PRIMARY KEY (ID_TEMA)
);

CREATE TABLE ITEM_TEMA (
    ID_ITEM_TEMA INT NOT NULL AUTO_INCREMENT,
    ID_TEMA INT,
    NOME_ITEM VARCHAR (30),
    CONSTRAINT PK_ITEM_TEMA PRIMARY KEY (ID_ITEM_TEMA),
    CONSTRAINT FK_ITEM_TEMA_TEMA FOREIGN KEY(ID_TEMA) REFERENCES TEMA (ID_TEMA)

);

CREATE TABLE ALUGUEL (
    ID_ALUGUEL INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT,
    ID_TEMA INT,
    VALOR DOUBLE,
    QUANTIDADE INT,
    CONSTRAINT PK_ALUGUEL PRIMARY KEY (ID_ALUGUEL),
    CONSTRAINT FK_ALUGUEL_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
    CONSTRAINT FK_ALUGUEL_TEMA FOREIGN KEY (ID_TEMA) REFERENCES TEMA (ID_TEMA)

);

CREATE TABLE ALUGUEL2 (
    ID_ALUGUEL INT AUTO_INCREMENT ,
    ID_CLIENTE INT,
    ID_TEMA INT,
    VALOR DOUBLE,
    QUANTIDADE INT,
    PRIMARY KEY (ID_ALUGUEL),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
    FOREIGN KEY (ID_TEMA) REFERENCES TEMA (ID_TEMA)

);





-- INSERÇÃO DE TEMAS 

INSERT INTO TEMA VALUES(NULL,"STAR WARS", 100, 2);
INSERT INTO TEMA (NOME_TEMA, VALOR_TEMA,QUANTIDADE_TEMA) 
     VALUES ("SUPERMAN", 80, 1);
INSERT INTO TEMA (QUANTIDADE_TEMA, NOME_TEMA, VALOR_TEMA) 
     VALUES ( 1, "BARCELONA", 120);

INSERT INTO TEMA (NOME_TEMA, VALOR_TEMA,QUANTIDADE_TEMA) 
     VALUES ("CHAPOLIN", 200, 1);

INSERT INTO TEMA (NOME_TEMA, VALOR_TEMA,QUANTIDADE_TEMA) 
     VALUES ("CAPITAN MARVEL", 250, 4);

INSERT INTO TEMA (NOME_TEMA, VALOR_TEMA,QUANTIDADE_TEMA) 
     VALUES ("MULHER MARAVILHA", 250, 3);

INSERT INTO TEMA (NOME_TEMA, VALOR_TEMA,QUANTIDADE_TEMA) 
     VALUES ("FLASH", 80, 1);

INSERT INTO TEMA (NOME_TEMA, VALOR_TEMA,QUANTIDADE_TEMA) 
     VALUES ("POKEMON", 50, 1);

INSERT INTO TEMA (NOME_TEMA, VALOR_TEMA,QUANTIDADE_TEMA) 
     VALUES ("SELEÇÃO BRASILEIRA", 30, 5);

INSERT INTO TEMA (NOME_TEMA, VALOR_TEMA,QUANTIDADE_TEMA) 
     VALUES ("PERNALONGA", 100, 2);


-- INSERÇÃO DE ITENS TEMAS 
 --  ITENS TEMA STAR WARS
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (1, "FANTASIA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (1, "LIGHT SABER");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (1, "MILENIUM FALCON");

-- ITENS TEMA SUPERMAN

INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (2, "FANTASIA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (2, "KRIPTONITA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (2, "BONECO");

-- ITENS TEMA BARCELONA

INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (3, "FlÂMULA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (3, "TOALHA DE MESA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (3, "CAMISA");

-- ITENS TEMA CHAPOLIN

INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (4, "FANTASIA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (4, "FUNDO DE MESA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (4, "BOLO FAKE");

-- ITENS CAPITAN MARVEL

INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (5, "BOLO FAKE");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (5, "FANTASIA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (5, "BONECA");

-- ITENS MULHER MARAVILHA

INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (6, "BONECA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (6, "TOALHA MESA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (6, "FANTASIA");

-- ITENS FLASH

INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (7, "FUNDO DE MESA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (7, "MESA DE PERSONAGENS");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (7, "FANTASIA");

-- ITENS POKEMON
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (8, "MESA DE PERSONAGENS");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (8, "PIKACHU");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (8, "TOALHA MESA");

-- ITENS SELEÇÃO BRASILEIRA
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (9, "TOALHA MESA CAMPO FUTEBOL");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (9, "MÁSCARA NEYMAR");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (9, "CAMISA FELIPÃO");

-- ITENS PERNALONGA

INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (10, "FANTASIA");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (10, "MESA DE PERSONAGENS");
INSERT INTO ITEM_TEMA (ID_TEMA, NOME_ITEM) VALUES (10, "BOLO FAKE");

-- INSERÇÃO CLIENTE

INSERT INTO CLIENTE (NOME_CLIENTE) VALUES ("SOPHIA PNHEIRO ROSA");
INSERT INTO CLIENTE (NOME_CLIENTE) VALUES ("JOÃO BATISTA NETO");
INSERT INTO CLIENTE (NOME_CLIENTE) VALUES ("PAULA GIRALDELI");
INSERT INTO CLIENTE (NOME_CLIENTE) VALUES ("CÉLIA RODRIGUES");

-- INSERÇÃO FESTA

INSERT INTO FESTA VALUES 
(NULL, 1, SYSDATE(), "1900", "2300", "RUA 10 DE MAIO, 200 - ZONA 07");
INSERT INTO FESTA VALUES 
(NULL, 3, SYSDATE() + INTERVAL 10 DAY, "2000", "0100", "AV. TIRADENTES, 867 - ZONA 01");

-- INSERÇÃO ALUGUEL

INSERT ALUGUEL VALUES (NULL, 1, 1, 90, 1);
INSERT ALUGUEL VALUES (NULL, 2, 7, 80, 1);






-- CONSULTA TODOS OS TEMAS E SEUS ITENS
SELECT T.NOME_TEMA, I.NOME.ITEM 
  FROM TEMA T RIGHT JOIN ITEM_TEMA I 
    ON I.ID_TEMA = T.ID_TEMA;

-- CONSULTA CLIENTES QUE TÊM FESTA

SELECT C.NOME_CLIENTE, F.DATA_FESTA 
  FROM FESTA F LEFT JOIN CLIENTE C 
    ON F.ID_CLIENTE = C.ID_CLIENTE;

-- CONSULTA CLIENTES E TEMAS ALUGADOS

SELECT C.NOME_CLIENTE, T.NOME_TEMA 
  FROM ALUGUEL A 
  INNER JOIN CLIENTE C 
    ON A.ID_CLIENTE = C.ID_CLIENTE
  INNER JOIN TEMA T
    ON A.ID_TEMA = T.ID_TEMA;  

SELECT COUNT(I.ID_ITEM_TEMA)
     FROM TEMA T RIGHT JOIN ITEM_TEMA I
     ON I.ID_ITEM = T.ID_ITEM
     GROUP BY I.NOME_TEMA;

-- RETIRAR A MESA DE PERSONAGENS DO POKEMON E ATRIBUIR AO TEMA BARCELONA,
-- EXECUTE A QUERY ACIMA NOVAMENTE, O RESULTADO DEVE SER 2 ITENS POKEMON E 
-- 4 ITENS BARCELONA
UPDATE ITEM_TEMA SET ID_TEMA = 3 WHERE ID_ITEM_TEMA = 22;

-- CONTABILIZAR OS ALUGUEIS
SELECT SUM(VALOR) FROM ALUGUEL;

-- MOSTRANDO A SOMA POR CLIENTE
SELECT C.NOME_CLIENTE, SUM(A.VALOR) VALOR FROM ALUGUEL A INNER JOIN CLIENTE C ON A.ID_CLIENTE = C.ID_CLIENTE
GROUP BY A.ID_CLIENTE;